### ISSUE TITLE
PHP5.6 :  symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by PatricNox** [eXolnet/homebrew-deprecated#11]
I'm trying to install PHP 5.6 version using homebrew, tap'ed on homebrew-deprecated, and I get this as an faulty error:

```
Last 15 lines from /Users/lia/Library/Logs/Homebrew/php@5.6/03.make:
      _load_all_certs_from_file in openssl.o
  "_sk_value", referenced from:
      _zif_openssl_x509_parse in openssl.o
      _zif_openssl_csr_new in openssl.o
      _zif_openssl_pkcs7_verify in openssl.o
      _php_openssl_parse_config in openssl.o
      _php_openssl_sockop_set_option in xp_ssl.o
      _capture_peer_certs in xp_ssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/libphp5.bundle] Error 1
make: *** Waiting for unfinished jobs....
warning: no debug symbols in executable (-arch x86_64)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ext/opcache/.libs/opcache.a(shared_alloc_shm.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ext/opcache/.libs/opcache.a(shared_alloc_shm.o) has no symbols
```

High Sierra, OpenSSL 1.0.2t.
I've runned `brew update` and `brew upgrade` prior to `brew install php@5.6`.

Any ideas?
Regards.

**Comment by PatricNox** [comment]
This solved it for me. 🎉 
https://github.com/gruntjs/grunt-contrib-sass/issues/229#issuecomment-531113100

**Comment by PatricNox** [comment]
This issue solves by using openSSL1.0.2 instead of 1.1.x
https://github.com/eXolnet/homebrew-deprecated/issues/9

Though, I'm already using 1.0.2t.

**Comment by rbrisita** [comment]
Facing this same issue. The issue #9 states success with version 1.0.2s. I'm looking into how to get that version now.

**Comment by rbrisita** [comment]
Tried:
```
wget https://homebrew.bintray.com/bottles/openssl-1.0.2s.sierra.bottle.tar.gz
brew install -f openssl-1.0.2s.sierra.bottle.tar.gz
brew install php@5.6
```
The result was still the same about missing symbols. I had the environment variables: LDFLAGS, CPPFLAGS, and PATH set to openssl v1.0.2s and verified it through the command line.

Looking forward to a fix here but in the meantime I'm using docker.

**Comment by rbrisita** [comment]
One can also install older versions with:

`curl -s https://php-osx.liip.ch/install.sh | bash -s 5.6`

from https://php-osx.liip.ch/ and activate by `export PATH=/usr/local/php5/bin:$PATH`

**Comment by pgrenaud** [comment]
We won't be able to provide support to older macOS version (other than Catalina). Sorry about this.
