### ISSUE TITLE
Bottle for macOS Catalina

### ISSUE THREAD

**Issue by PimLab** [eXolnet/homebrew-deprecated#12]
Hey there!

Did you plan a Bootle for the new macOS or will Mojave Bootle will work with it?

Beste Wishes!

**Comment by pgrenaud** [comment]
Hi @PimLab,

Currently, all Mojave bottles work out-of-the-box with Catalina. If at some point in the future one the bottle is no longer compatible, I will re-bottle the formulae. Just let us know if you notice that something isn't working right!

Thanks!
