### ISSUE TITLE
PHP7.1 is missing php-fpm.conf and php.ini

### ISSUE THREAD

**Issue by KoenPasman** [eXolnet/homebrew-deprecated#15]
After installing php@7.1 on Catalina i'm missing several config files, like php-fpm.conf, php-fpm.d directory and php.ini. 

I've tried reinstalling but to no avail. Im on this version of brew:
```
$ brew -v
Homebrew 2.2.1
Homebrew/homebrew-core (git revision dd63; last commit 2019-12-18)
Homebrew/homebrew-cask (git revision 26f014; last commit 2019-12-18)
```

**Comment by TheLalaMan** [comment]
Same for me, would be great if that could be fixed!

**Comment by pgrenaud** [comment]
Hi!

Thanks for reporting the issue.

Indeed, the php@7.1 bottle is incomplete, where the ini files are missing. It happened in the past and I still don't know why this happened.

I've rebuild and deployed a new bottle. It should now have the missing files. Please run `brew update; brew reinstall php@7.1` to update your tap and reinstall php 7.1.

Have a nice day!

**Comment by pgrenaud** [comment]
@TheLalaMan I won't be building bottles for older macOS versions, but it should work fine, just taking a little bit longer.

**Comment by KoenPasman** [comment]
Thanks for the quick resolve! Works now :)
