### ISSUE TITLE
PHP 7.1 - configure: error: Cannot find zlib

### ISSUE THREAD

**Issue by ElPodge** [eXolnet/homebrew-deprecated#16]
I'm trying to install php@7.1 on Catalina 10..15.2. Started well but ended with an error on ZLIB.
Any help ?
I do it using valet :
> t$ valet use php@7.1
> Installing php@7.1...
> [php@7.1] is not installed, installing it now via Brew... 🍻
> ==> Installing php@7.1 from exolnet/deprecated
> ==> Downloading https://homebrew.bintray.com/bottles-deprecated/php@7.1-7.1.33.catalina.bottle.1.tar.gz
> curl: (22) The requested URL returned error: 404 Not Found
> Error: Failed to download resource "php@7.1"
> Download failed: https://homebrew.bintray.com/bottles-deprecated/php@7.1-7.1.33.catalina.bottle.1.tar.gz
> Warning: Bottle installation failed: building from source.
> ==> Downloading https://www.php.net/distributions/php-7.1.33.tar.xz
> ==> Patching
> patching file acinclude.m4
> Hunk #1 succeeded at 444 (offset 3 lines).
> Hunk #2 succeeded at 459 (offset 3 lines).
> Hunk #3 succeeded at 494 (offset 3 lines).
> Hunk #4 succeeded at 506 (offset 3 lines).
> Hunk #5 succeeded at 2541 (offset 122 lines).
> ==> ./buildconf --force
> ==> ./configure --prefix=/usr/local/Cellar/php@7.1/7.1.33 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/7.1 --with-config-file-path=/usr/local/etc/php/7.1 --with-config-file-scan-dir=/usr/local/etc/php/7.1/conf.d --with-pear=/usr/local/Cellar/php@7.1/7.1.33/share/php@7.1/pear --enable-bcmath --enable-calendar --enable-dba --enable-dtrace --enable-exif --enable-ftp --enable-fpm --enable-intl --enable-mbregex --enable-mbstring --enable-mysqlnd --enable-opcache-file --enable-pcntl --enable-phpdbg --enable-phpdbg-webhelper --enable-shmop --enable-soap --enable-sockets --enable-sysvmsg --enable-sysvsem --enable-sysvshm --enable-wddx --enable-zip --with-apxs2=/usr/local/opt/httpd/bin/apxs --with-bz2=/usr --with-curl=/usr/local/opt/curl-openssl --with-fpm-user=_www --with-fpm-group=_www --with-freetype-dir=/usr/local/opt/freetype --with-gd --with-gettext=/usr/local/opt/gettext --with-gmp=/usr/local/opt/gmp --with-iconv=/usr --with-icu-dir=/usr/local/opt/icu4c --with-jpeg-dir=/usr/local/opt/jpeg --with-kerberos=/usr --with-layout=GNU --with-ldap=/usr/local/opt/openldap --with-ldap-sasl=/usr --with-libedit=/usr --with-libxml-dir=/usr --with-libzip --with-mcrypt=/usr/local/opt/mcrypt --with-mhash=/usr --with-mysql-sock=/tmp/mysql.sock --with-mysqli=mysqlnd --with-ndbm=/usr --with-openssl=/usr/local/opt/openssl@1.1 --with-pdo-dblib=/usr/local/opt/freetds --with-pdo-mysql=mysqlnd --with-pdo-odbc=unixODBC,/usr/local/opt/unixodbc --with-pdo-pgsql=/usr/local/opt/libpq --with-pdo-sqlite=/usr/local/opt/sqlite --with-pgsql=/usr/local/opt/libpq --with-pic --with-png-dir=/usr/local/opt/libpng --with-pspell=/usr/local/opt/aspell --with-sqlite3=/usr/local/opt/sqlite --with-tidy=/usr/local/opt/tidy-html5 --with-unixODBC=/usr/local/opt/unixodbc --with-webp-dir=/usr/local/opt/webp --with-xmlrpc --with-xsl=/usr --with-zlib=/usr
> Last 15 lines from /Users/laurent/Library/Logs/Homebrew/php@7.1/02.configure:
> checking for CRYPTO_free in -lcrypto... yes
> checking for SSL_CTX_set_ssl_version in -lssl... yes
> checking for PCRE library to use... bundled
> checking whether to enable PCRE JIT functionality... yes
> checking whether to enable the SQLite3 extension... yes
> checking for sqlite3 files in default path... found in /usr/local/opt/sqlite
> checking for SQLite 3.3.9+... checking for sqlite3_prepare_v2 in -lsqlite3... yes
> found
> checking for sqlite3_key in -lsqlite3... no
> checking for sqlite3_column_table_name in -lsqlite3... yes
> checking for sqlite3_errstr in -lsqlite3... yes
> checking for sqlite3_load_extension in -lsqlite3... yes
> checking for ZLIB support... yes
> checking if the location of ZLIB install directory is defined... no
> configure: error: Cannot find zlib

**Comment by UnnikrishnanBhargavakurup** [comment]
any idea hw to fix this?

**Comment by melissabillias** [comment]
Try `apt-get install --reinstall zlibc zlib1g zlib1g-dev`

I had zlib1g already installed and was getting that error during php@7.1 install. I didn't try installing them one at a time, so I don't know which actually solved the problem.

**Comment by pgrenaud** [comment]
Hi!

Thank you for your interest in this repository. Unfortunately, this repository will now be archived with no further actions. We are sorry for the inconvenience.

**Why are we closing this repository?** This repository was only meant as a temporary measure, not a permanent one. Its only purpose was to ease the transition, considering that formulae from the homebrew-core tap are removed almost the day they became unsupported by the vendor. We needed a few more months to allow us to upgrade the code base of the various projects we have. But it was always with the intention of doing those upgrades, not by relying on a repository to keep old php versions artificially alive. We do not condone the use of deprecated software that could lead to serious security vulnerabilities.

**Why are we not redirecting to another repository?** Redirecting to another repository could be interpreted as an endorsement of said repository. If we were to do such a thing, we would not do it without vetting it first. And we do not wish to put the time and energy required in a vetting process of a third party repository. As the reason why a vetting process would be required, consider this. Before installing a software library on all our developer computers from an untrusted source, we would need to make sure that this software library is free from any malicious code (Trojan, ransomware, etc.), both in the repository itself and in the packaged binaries (the homebrew bottles, if any).

Thank you for your understanding.
