### ISSUE TITLE
MacOs,  brew install exolnet/deprecated/php@5.6 errors

### ISSUE THREAD

**Issue by hwbaker** [eXolnet/homebrew-deprecated#19]
When I compile php5.6, there are some errors here：

Last 15 lines from /Users/hwbaker/Library/Logs/Homebrew/php@5.6/03.make:
typedef struct rsa_st RSA;
               ^
/private/tmp/php@5.6-20200212-21126-mtwg9a/php-5.6.40/ext/openssl/openssl.c:3619:6: error: incomplete definition of type 'struct rsa_st'
                                        OPENSSL_PKEY_SET_BN(Z_ARRVAL_PP(data), rsa, d);
                                        ^                                      ~~~
/private/tmp/php@5.6-20200212-21126-mtwg9a/php-5.6.40/ext/openssl/openssl.c:3548:9: note: expanded from macro 'OPENSSL_PKEY_SET_BN'
                        _type->_name = BN_bin2bn(                                                                       \
                        ~~~~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'struct rsa_st'
typedef struct rsa_st RSA;
               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [ext/openssl/openssl.lo] Error 1
make: *** Waiting for unfinished jobs....

**Comment by 2ge** [comment]
@hwbaker I run into exactly same error:

```
==> Reinstalling exolnet/deprecated/php@5.6 
==> Downloading https://php.net/get/php-5.6.40.tar.xz/from/this/mirror
Already downloaded: /Users/brano/Library/Caches/Homebrew/downloads/ab2ea146f7d8c5258e6d33e9522dac5528cbc3e966bc6e5689fa57860dbb5441--php-5.6.40.tar.xz
==> Patching
patching file acinclude.m4
Hunk #1 succeeded at 444 (offset 3 lines).
Hunk #2 succeeded at 459 (offset 3 lines).
Hunk #3 succeeded at 494 (offset 3 lines).
Hunk #4 succeeded at 506 (offset 3 lines).
Hunk #5 succeeded at 2500 with fuzz 2 (offset 81 lines).
patching file Zend/zend_compile.h
patching file Zend/zend_execute.h
==> ./buildconf --force
==> ./configure --prefix=/usr/local/Cellar/php@5.6/5.6.40 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/
==> make
Last 15 lines from /Users/brano/Library/Logs/Homebrew/php@5.6/03.make:
typedef struct rsa_st RSA;
               ^
/private/tmp/php@5.6-20200228-27440-11nsjkm/php-5.6.40/ext/openssl/openssl.c:3619:6: error: incomplete definition of type 'struct rsa_st'
                                        OPENSSL_PKEY_SET_BN(Z_ARRVAL_PP(data), rsa, d);
                                        ^                                      ~~~
/private/tmp/php@5.6-20200228-27440-11nsjkm/php-5.6.40/ext/openssl/openssl.c:3548:9: note: expanded from macro 'OPENSSL_PKEY_SET_BN'
                        _type->_name = BN_bin2bn(                                                                       \
                        ~~~~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'struct rsa_st'
typedef struct rsa_st RSA;
               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [ext/openssl/openssl.lo] Error 1
make: *** Waiting for unfinished jobs....

```

I am on MacOS Sierra, reinstalling OpenSSL to 1.0 didnt help.

**Comment by sqrtcat** [comment]
i also get this problem on High Sierra

**Comment by mavimedia** [comment]
Same on Mojave

Updating Homebrew...
==> Installing php@5.6 from exolnet/deprecated
==> Downloading https://php.net/get/php-5.6.40.tar.xz/from/this/mirror
Already downloaded: /Users/aydin/Library/Caches/Homebrew/downloads/ab2ea146f7d8c5258e6d33e9522dac5528cbc3e966bc6e5689fa57860dbb5441--php-5.6.40.tar.xz
==> Patching
patching file acinclude.m4
Hunk #1 succeeded at 444 (offset 3 lines).
Hunk #2 succeeded at 459 (offset 3 lines).
Hunk #3 succeeded at 494 (offset 3 lines).
Hunk #4 succeeded at 506 (offset 3 lines).
Hunk #5 succeeded at 2500 with fuzz 2 (offset 81 lines).
patching file Zend/zend_compile.h
patching file Zend/zend_execute.h
==> ./buildconf --force
==> ./configure --prefix=/usr/local/Cellar/php@5.6/5.6.40 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr/local/etc/php/5.
==> make
Last 15 lines from /Users/aydin/Library/Logs/Homebrew/php@5.6/03.make:
        if (!dsa->p || !dsa->q || !dsa->g) {
                                   ~~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:107:16: note: forward declaration of 'struct dsa_st'
typedef struct dsa_st DSA;
               ^
/private/tmp/php@5.6-20200602-8735-1fsxhwc/php-5.6.40/ext/openssl/openssl.c:3560:9: error: incomplete definition of type 'struct dsa_st'
        if (dsa->priv_key || dsa->pub_key) {
            ~~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:107:16: note: forward declaration of 'struct dsa_st'
typedef struct dsa_st DSA;
               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [ext/openssl/openssl.lo] Error 1
make: *** Waiting for unfinished jobs....

**Comment by pgrenaud** [comment]
Hi!

Thank you for your interest in this repository. Unfortunately, this repository will now be archived with no further actions. We are sorry for the inconvenience.

**Why are we closing this repository?** This repository was only meant as a temporary measure, not a permanent one. Its only purpose was to ease the transition, considering that formulae from the homebrew-core tap are removed almost the day they became unsupported by the vendor. We needed a few more months to allow us to upgrade the code base of the various projects we have. But it was always with the intention of doing those upgrades, not by relying on a repository to keep old php versions artificially alive. We do not condone the use of deprecated software that could lead to serious security vulnerabilities.

**Why are we not redirecting to another repository?** Redirecting to another repository could be interpreted as an endorsement of said repository. If we were to do such a thing, we would not do it without vetting it first. And we do not wish to put the time and energy required in a vetting process of a third party repository. As the reason why a vetting process would be required, consider this. Before installing a software library on all our developer computers from an untrusted source, we would need to make sure that this software library is free from any malicious code (Trojan, ransomware, etc.), both in the repository itself and in the packaged binaries (the homebrew bottles, if any).

Thank you for your understanding.
