### ISSUE TITLE
Why is this here

### ISSUE THREAD

**Issue by Colmbus72** [eXolnet/homebrew-deprecated#20]
https://github.com/eXolnet/homebrew-deprecated/blob/8480601002563e78dc285f91ac4b178d45220cc0/Formula/php%405.6.rb#L415-L502

**Comment by pgrenaud** [comment]
Hi!

Thank you for your interest in this repository. Unfortunately, this repository will now be archived with no further actions. We are sorry for the inconvenience.

**Why are we closing this repository?** This repository was only meant as a temporary measure, not a permanent one. Its only purpose was to ease the transition, considering that formulae from the homebrew-core tap are removed almost the day they became unsupported by the vendor. We needed a few more months to allow us to upgrade the code base of the various projects we have. But it was always with the intention of doing those upgrades, not by relying on a repository to keep old php versions artificially alive. We do not condone the use of deprecated software that could lead to serious security vulnerabilities.

**Why are we not redirecting to another repository?** Redirecting to another repository could be interpreted as an endorsement of said repository. If we were to do such a thing, we would not do it without vetting it first. And we do not wish to put the time and energy required in a vetting process of a third party repository. As the reason why a vetting process would be required, consider this. Before installing a software library on all our developer computers from an untrusted source, we would need to make sure that this software library is free from any malicious code (Trojan, ransomware, etc.), both in the repository itself and in the packaged binaries (the homebrew bottles, if any).

Thank you for your understanding.
