### ISSUE TITLE
php-fpm.conf and php.ini does not exist

### ISSUE THREAD

**Issue by wwp66650** [eXolnet/homebrew-deprecated#3]
php-fpm.log    >> ERROR: failed to load configuration file '/usr/local/etc/php/5.6/php-fpm.conf'

**Comment by maxxer** [comment]
As a workaround you can pick them from another php version and put them in `/usr/local/etc/php/5.6/`, adjusting some lines

**Comment by pgrenaud** [comment]
Thanks for reporting the issue.

Hum, both php@5.6 and php@7.0 bottles are incomplete, where the ini files are missing. I don't know why this happened. I'll have to find the issue and rebuild the bottles.

In the meantime, can you try to install from source using `brew install php@5.6 --build-from-source` to see if that fixes the issue?

**Comment by yifanes** [comment]
@wwp66650 Just install it by -s
@pgrenaud pls rebuild the bottles.

**Comment by renalpha** [comment]
got exactly the same problem, I want to run php56 as FPM with a different port. Will try to run from source

**Comment by maxxer** [comment]
> Hum, both php@5.6 and php@7.0 bottles are incomplete, where the ini files are missing. I don't know why this happened. I'll have to find the issue and rebuild the bottles.

to be precise they're not the ini file but the fpm conf ones

**Comment by renalpha** [comment]
Yifanes tip solved my issue. thanks.

**Comment by pgrenaud** [comment]
Hi!

I've rebuild and deployed 2 new bottles, for php 5.6 and 7.0. Both should now have the missing files.

Please run `brew update; brew reinstall php@5.6` to update your tap and reinstall php 5.6.

Have a nice day!
