### ISSUE TITLE
installing PHP 5.6 failed; errors reference struct dsa_st

### ISSUE THREAD

**Issue by donnamcmaster** [eXolnet/homebrew-deprecated#30]
First install of developer tools on a new MacBook running Catalina 10.15.7. Followed instructions at https://getgrav.org/blog/macos-catalina-apache-multiple-php-versions: 

1. "$ xcode-select --install" failed so I installed "Command Line Tools for Xcode 12.1 GM seed" from https://developer.apple.com/download/more/?=command%20line%20tools

2. "$ brew tap exolnet/homebrew-deprecated" succeeded

3. "$ brew install --build-from-source php@5.6" ran through a lot of downloads & installs, then failed (full log is attached [exolnet-php56-log.txt](https://github.com/eXolnet/homebrew-deprecated/files/5432451/exolnet-php56-log.txt)): 

==> Installing exolnet/deprecated/php@5.6
==> Patching
==> ./buildconf --force
==> ./configure --prefix=/usr/local/Cellar/php@5.6/5.6.40 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --wit
==> make
Last 15 lines from /Users/donna/Library/Logs/Homebrew/php@5.6/03.make:
        if (!dsa->p || !dsa->q || !dsa->g) {
                                   ~~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:107:16: note: forward declaration of 'struct dsa_st'
typedef struct dsa_st DSA;
               ^
/private/tmp/php@5.6-20201023-19032-tp8uwy/php-5.6.40/ext/openssl/openssl.c:3560:9: error: incomplete definition of type 'struct dsa_st'
        if (dsa->priv_key || dsa->pub_key) {
            ~~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:107:16: note: forward declaration of 'struct dsa_st'
typedef struct dsa_st DSA;
               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [ext/openssl/openssl.lo] Error 1
make: *** Waiting for unfinished jobs....

**Comment by donnamcmaster** [comment]
I did look at other issues, including #29 and #14 and they may be related, but I'm not savvy enough to figure out how. Thanks for any help.

**Comment by glendonyeo** [comment]
@donnamcmaster have you manually add the openssl patches and reinstall?

**Comment by tranducitdev** [comment]
cannot install Command Line Tool v11 on BigSur

> @donnamcmaster have you manually add the openssl patches and reinstall?
> 
> i would suggest you to do the following,
> 
> 1. Install Command Line Tool v11
> 2. follow the instruction over this reply [#23 (comment)](https://github.com/eXolnet/homebrew-deprecated/issues/23#issuecomment-704825266)
> 
> Hope it help

Cannot install Command Line Tool v11 on BigSur.

**Comment by glendonyeo** [comment]
> cannot install Command Line Tool v11 on BigSur
> 
> > @donnamcmaster have you manually add the openssl patches and reinstall?
> > i would suggest you to do the following,
> > 
> > 1. Install Command Line Tool v11
> > 2. follow the instruction over this reply [#23 (comment)](https://github.com/eXolnet/homebrew-deprecated/issues/23#issuecomment-704825266)
> > 
> > Hope it help
> 
> Cannot install Command Line Tool v11 on BigSur.

Stop Using Pre-Release Product

**Comment by ammmze** [comment]
I would recommend checking out https://github.com/shivammathur/homebrew-php. I just found out about it but it as of now is actively maintained unlike exolnet's version here.

**Comment by pgrenaud** [comment]
Hi!

Thank you for your interest in this repository. Unfortunately, this repository will now be archived with no further actions. We are sorry for the inconvenience.

**Why are we closing this repository?** This repository was only meant as a temporary measure, not a permanent one. Its only purpose was to ease the transition, considering that formulae from the homebrew-core tap are removed almost the day they became unsupported by the vendor. We needed a few more months to allow us to upgrade the code base of the various projects we have. But it was always with the intention of doing those upgrades, not by relying on a repository to keep old php versions artificially alive. We do not condone the use of deprecated software that could lead to serious security vulnerabilities.

**Why are we not redirecting to another repository?** Redirecting to another repository could be interpreted as an endorsement of said repository. If we were to do such a thing, we would not do it without vetting it first. And we do not wish to put the time and energy required in a vetting process of a third party repository. As the reason why a vetting process would be required, consider this. Before installing a software library on all our developer computers from an untrusted source, we would need to make sure that this software library is free from any malicious code (Trojan, ransomware, etc.), both in the repository itself and in the packaged binaries (the homebrew bottles, if any).

Thank you for your understanding.
