### ISSUE TITLE
As this is broken, point users to the working shivammathur/homebrew-php tap

### ISSUE THREAD

**Issue by marc-guenther** [eXolnet/homebrew-deprecated#32]
As:
- this tap **doesn't work** anymore,
- but still is the **top hit** in Google,

maybe we could save lots of users several hours of time **each**, by putting a link in the README to point them to the tap that **works perfectly fine out of the box**:

#### Homebrew tap for PHP 5.6 to 8.1:
- https://github.com/shivammathur/homebrew-php

**Comment by pgrenaud** [comment]
Hi!

Thank you for your interest in this repository. Unfortunately, this repository will now be archived with no further actions. We are sorry for the inconvenience.

**Why are we closing this repository?** This repository was only meant as a temporary measure, not a permanent one. Its only purpose was to ease the transition, considering that formulae from the homebrew-core tap are removed almost the day they became unsupported by the vendor. We needed a few more months to allow us to upgrade the code base of the various projects we have. But it was always with the intention of doing those upgrades, not by relying on a repository to keep old php versions artificially alive. We do not condone the use of deprecated software that could lead to serious security vulnerabilities.

**Why are we not redirecting to another repository?** Redirecting to another repository could be interpreted as an endorsement of said repository. If we were to do such a thing, we would not do it without vetting it first. And we do not wish to put the time and energy required in a vetting process of a third party repository. As the reason why a vetting process would be required, consider this. Before installing a software library on all our developer computers from an untrusted source, we would need to make sure that this software library is free from any malicious code (Trojan, ransomware, etc.), both in the repository itself and in the packaged binaries (the homebrew bottles, if any).

Thank you for your understanding.
