### ISSUE TITLE
Make install fails on Sierra for PHP 5.6.40 (and below)

### ISSUE THREAD

**Issue by PierreRe** [eXolnet/homebrew-deprecated#6]
Hello and Thanks for carrying on PHP 5.6 on brew!

I do have an issue installing these deprecated packages on Sierra. Compilation seems to run fine and make finishes without errors.

However, make install stops after an error. Here is a log:

`Last 15 lines from /Users/SOMEUSER/Library/Logs/Homebrew/php@5.6/04.make:
make: [install-sapi] Error 1 (ignored)
make: /private/tmp/php@5.6-20190328-36797-159l7nq/php-5.6.40/build/shtool: Permission denied
make: *** [install-cgi] Error 1
make: *** [install-cli] Error 1
mkdir: /usr/local/Cellar/php@5.6/5.6.40/lib/php: File exists
Installing shared extensions:     /usr/local/Cellar/php@5.6/5.6.40/lib/php/20131226/
/usr/local/opt/httpd/lib/httpd/build/instdso.sh SH_LIBTOOL='/usr/local/opt/apr/libexec/build-1/libtool' libs/libphp5.so /usr/local/Cellar/php@5.6/5.6.40/lib/httpd/modules
/usr/local/opt/apr/libexec/build-1/libtool --mode=install install libs/libphp5.so /usr/local/Cellar/php@5.6/5.6.40/lib/httpd/modules/
libtool: install: install libs/libphp5.so /usr/local/Cellar/php@5.6/5.6.40/lib/httpd/modules/libphp5.so
Warning!  dlname not found in /usr/local/Cellar/php@5.6/5.6.40/lib/httpd/modules/libphp5.so.
Assuming installing a .so rather than a libtool archive.
chmod 755 /usr/local/Cellar/php@5.6/5.6.40/lib/httpd/modules/libphp5.so
Installing PHP FPM config:        /usr/local/etc/php/5.6/
Installing PHP FPM man page:      /usr/local/Cellar/php@5.6/5.6.40/share/man/man8/
Installing PHP FPM status page:   /usr/local/Cellar/php@5.6/5.6.40/share/php/fpm/`

Is anyone else having this problem? Was anybody able to solve it?

Cheers,
Pierre

**Comment by pgrenaud** [comment]
Hi!

We do not maintain bottles for Sierra and we do not test for this platform. We only do so for Mojave.

Let me see if I can pop a new VM to test the install on Sierra. I'll let you know what I find.

Regards.

**Comment by NicoxDJ** [comment]
Anything? I have that problem too, but i think my problem is in ./configure

`==> Installing php@5.6 from exolnet/deprecated
==> Downloading https://php.net/get/php-5.6.40.tar.xz/from/this/mirror
Already downloaded: /Users/Nicox/Library/Caches/Homebrew/downloads/ab2ea146f7d8c5258e6d33e9522dac5528cbc3e966bc6e5689fa57860dbb5441--php-5.6.40.tar.xz
==> Patching
patching file acinclude.m4
Hunk #1 succeeded at 444 (offset 3 lines).
Hunk #2 succeeded at 459 (offset 3 lines).
Hunk #3 succeeded at 494 (offset 3 lines).
Hunk #4 succeeded at 506 (offset 3 lines).
Hunk #5 succeeded at 2500 with fuzz 2 (offset 81 lines).
patching file Zend/zend_compile.h
patching file Zend/zend_execute.h
==> ./buildconf --force
==> ./configure --prefix=/usr/local/Cellar/php@5.6/5.6.40 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-fi
Last 15 lines from /Users/Nicox/Library/Logs/Homebrew/php@5.6/02.configure:
checking for zlib version >= 1.2.0.4... 1.2.8
checking for gzgets in -lz... yes
checking whether to enable bc style precision math functions... yes
checking for BZip2 support... yes
checking for BZ2_bzerror in -lbz2... yes
checking whether to enable calendar conversion support... yes
checking whether to enable ctype functions... yes
checking for cURL support... yes
checking for cURL 7.10.5 or greater... libcurl 7.64.1
checking for SSL support in libcurl... yes
checking how to run the C preprocessor... clang -E
checking for openssl support in libcurl... no
checking for gnutls support in libcurl... no
checking for curl_easy_perform in -lcurl... no
configure: error: There is something wrong. Please check config.log for more information.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/exolnet/homebrew-deprecated/issues`

in config.log i have a lot of errors

**Comment by PierreRe** [comment]
> Hi!
> 
> We do not maintain bottles for Sierra and we do not test for this platform. We only do so for Mojave.
> 
> Let me see if I can pop a new VM to test the install on Sierra. I'll let you know what I find.
> 
> Regards.

Thanks for looking into this!

**Comment by pgrenaud** [comment]
Hi!

We won't be able to provide bottles for Sierra and High Sierra.

Sorry about this.

Regards.
