### ISSUE TITLE
Install fails on Mojave

### ISSUE THREAD

**Issue by egoettelmann** [eXolnet/homebrew-deprecated#7]
Many thanks for your efforts of keeping these versions available.

After trying to install version 5.6 I am getting the following:
```
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.63.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
Abort trap: 6
```

Same result when trying to install version 7.0.

**Comment by nahuelhds** [comment]
I'm having the same issue.
I see that the dependency is set to icu4c but brew installs v64 when PHP5.6 needs 6.3

**Comment by pgrenaud** [comment]
Hi!

Thanks for reporting the issue.

Some dependencies got updated and homebrew seems to fail at installing from source when updating.

I've rebuild and deployed 2 new bottles, for php 5.6 and 7.0, which fixed the issue.

Please run `brew update; brew reinstall php@5.6; brew reinstall php@7.0` to update your tap and reinstall php 5.6 and 7.0.

Have a nice day!

**Comment by egoettelmann** [comment]
Works as expected.

Many thanks!
